file_format: "1"
id: puntero34
name: puntero34
type: shield
url: https://github.com/badjeff/puntero34/
requires: [xiao_ble]
exposes: []
features:
  - keys
siblings:
  - puntero34_left
  - puntero34_right
