# SPDX-License-Identifier: MIT

properties:
  irq-gpios:
    type: phandle-array
    description: Data ready gpio, INT pin on MLX90393

  calib-cycle:
    type: int
    default: 100
    description: count of auto calibration cycle

  woc-thd-xy-mul:
    type: int
    default: 30
    description: X-axis wake-on-change threshold multiplier

  woc-thd-z-mul:
    type: int
    default: 30
    description: X-axis wake-on-change threshold multiplier

  rpt-dzn-x:
    type: int
    default: 49
    description: X-axis deadzone

  rpt-dzn-y:
    type: int
    default: 49
    description: Y-axis deadzone

  rpt-dzn-z:
    type: int
    default: 49
    description: Z-axis deadzone
