# SPDX-License-Identifier: MIT

properties:
  irq-gpios:
    type: phandle-array
    description: Data ready gpio, INT pin on MLX90393

  no-x:
    type: boolean
    description: skip measure x axis on chip (default read xyz)
 
  no-y:
    type: boolean
    description: skip measure y axis on chip (default read xyz)

  no-z:
    type: boolean
    description: skip measure z axis on chip (default read xyz)

  calib-cycle:
    type: int
    default: 100
    description: count of auto calibration cycle

  ex-woc-thd-xy:
    type: int
    default: 0
    description: extra delta for XY-axis wake-on-change threshold

  ex-woc-thd-z:
    type: int
    default: 0
    description: extra delta for Z-axis wake-on-change threshold

  downshift:
    type: int
    default: 75
    description: |
      Maximum in-deadzone-reading allow in burst mode interrupts before 
      downshift to wake-on change mode.
      Interrupt interval is hardcode to ~20ms, default 75 * ~20ms = 1500ms downshift

  rpt-dzn-x:
    type: int
    default: 150
    description: X-axis deadzone

  rpt-dzn-y:
    type: int
    default: 150
    description: Y-axis deadzone

  rpt-dzn-z:
    type: int
    default: 150
    description: Z-axis deadzone
