# SPDX-License-Identifier: MIT

properties:
  irq-gpios:
    type: phandle-array
    description: Data ready gpio, INT pin on MLX90393

  calib-cycle:
    type: int
    default: 100
    description: count of auto calibration cycle

  woc-thd-xy:
    type: int
    default: 0
    description: extra delta for XY-axis wake-on-change threshold

  woc-thd-z:
    type: int
    default: 0
    description: extra delta for Z-axis wake-on-change threshold

  rpt-dzn-x:
    type: int
    default: 250
    description: X-axis deadzone

  rpt-dzn-y:
    type: int
    default: 200
    description: Y-axis deadzone

  rpt-dzn-z:
    type: int
    default: 200
    description: Z-axis deadzone
