identifier: waveshare_rp2040_zero
name: Waveshare RP2040 ZERO
type: mcu
arch: arm
flash: 2048
ram: 264
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - uart
  - gpio
  - adc
  - i2c
  - spi
  - hwinfo
  - watchdog
  - flash
  - dma
  - counter
